// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What is being done. The five acts of `rule:work-legibility`, exhaustive by construction.
 *
 * **The ordering is load-bearing**: it is the significance ranking used to pick one act out of a
 * compound command (`cd x && npm run lint && git push` is an act of shipping). Do not reorder
 * without reading `classify::classify_command`.
 */
export type Act = "probe" | "plan" | "edit" | "build" | "verify" | "delegate" | "ship";
