// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What this repository has of the convention, and whether it is current.
 */
export type Adoption = { 
/**
 * A `work-levels.json` was found, here or above.
 */
declared: boolean, 
/**
 * The gate is present in this repository.
 */
gate: boolean, 
/**
 * The gate is present and differs from the one this app ships.
 *
 * **Not acted on, only reported.** A file inside somebody's repository is theirs; rewriting it
 * because a newer one shipped would produce a diff they did not make and cannot explain. The
 * hook script in the user's own home is refreshed silently for exactly the opposite reason —
 * nobody reviews `~/.local/bin` (rule:attention-signals).
 */
gate_stale: boolean, };
