// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One directory whose agent is asking for something.
 */
export type AgentWaiting = { 
/**
 * Matches a tab by its working directory — the whole reason the hook is better than a bell.
 */
cwd: string, 
/**
 * `Notification` (it wants an answer) or `Stop` (it has finished).
 */
event: string, 
/**
 * What it said, when it said anything.
 */
message: string | null, 
/**
 * True when the harness is reporting an **idle prompt** rather than asking for anything.
 *
 * **The distinction the message itself refuses to make.** An idle prompt arrives worded *"Claude
 * is waiting for your input"* — which reads as a question, and is not one: it is a timer
 * noticing the prompt has sat empty since the agent finished. A permission request names what it
 * wants and genuinely blocks. Both are `Notification`, and shipping them as one mark meant the
 * panel could not answer "does anything actually want something from me?".
 *
 * The decision is made here rather than handed over as a raw kind, so an unfamiliar kind from a
 * future harness resolves the same way on every surface: not idle, therefore worth your
 * attention (`hooks::is_idle`).
 */
idle: boolean, };
