// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the AI harness in a project is doing, as far as its transcript says.
 *
 * Every field is optional because the transcript is Claude Code's own working file rather than an
 * API: an unfamiliar shape must cost information, never correctness.
 */
export type AgentSession = { session_id: string | null, model: string | null, branch: string | null, 
/**
 * ISO timestamp of the most recent turn.
 */
last_at: string | null, 
/**
 * What the model had in front of it on the last turn — a level, not a total. This is the number
 * that decides when a compact is due.
 */
context_tokens: bigint | null, 
/**
 * What it has written across the turns in view — a total.
 */
output_tokens: bigint, turns: number, 
/**
 * Which Claude home this was read from. Shown because the maintainer runs several, and "which
 * account is this" is exactly the question a shared machine makes hard to answer.
 */
home: string, };
