// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentWaiting } from "./AgentWaiting";

/**
 * Whether the agent hooks are in place, and what they have reported.
 */
export type AgentAttention = { 
/**
 * True when this project's Claude home runs our hook for every event we listen to.
 */
installed: boolean, 
/**
 * The directories that have asked for attention since the last time they were looked at.
 */
waiting: Array<AgentWaiting>, };
