// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One directory whose agent is asking for something.
 */
export type AgentWaiting = { 
/**
 * Matches a tab by its working directory — the whole reason the hook is better than a bell.
 */
cwd: string, 
/**
 * `Notification` (it wants an answer) or `Stop` (it has finished).
 */
event: string, 
/**
 * What it said, when it said anything.
 */
message: string | null, };
