// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppMenuLabels } from "./AppMenuLabels";

/**
 * The menu, as the frontend describes it: what it says, and which key asks for it.
 */
export type AppMenuSpec = { labels: AppMenuLabels, 
/**
 * Accelerator per action id, already in the menu's own spelling (`Cmd+T`).
 *
 * **From the shortcut store, which is the only place a binding lives.** Hard-coding these in
 * Rust is what the default menu did, and it is why `⌘W` closed the window instead of the tab:
 * a menu key equivalent is dispatched by AppKit *before* the webview sees the keystroke, so a
 * menu that disagrees with the user's own binding does not lose the argument — it wins it,
 * silently. An absent entry means the item shows no key, which is honest.
 */
keys: { [key in string]: string }, };
