// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every word the native application menu shows.
 *
 * **The words come from the frontend, the shape does not.** A macOS menu has rules about which
 * submenu holds what and in which order, and those are not the frontend's to decide — so `menu.rs`
 * owns the skeleton and this carries the strings that go into it. Typed field by field rather than
 * a map, so a menu item added here without a translation is a compile error on both sides instead
 * of a blank line in a menu (ADR-CORE-005).
 *
 * It is the frontend's because that is where the language lives: the catalogue in `src/i18n` is the
 * single source for every user-visible word, and the menu is rebuilt when the setting changes. A
 * second copy of these strings in Rust would be a second thing to translate and a first thing to
 * forget.
 */
export type AppMenuLabels = { about: string, settings: string, services: string, hide: string, hideOthers: string, showAll: string, quit: string, shell: string, newTab: string, closeTab: string, find: string, clear: string, edit: string, undo: string, redo: string, cut: string, copy: string, paste: string, selectAll: string, view: string, fontBigger: string, fontSmaller: string, fontReset: string, logs: string, tools: string, toolGit: string, toolFiles: string, toolActivity: string, toolDocker: string, toolAgent: string, toolChain: string, toolTmux: string, toolNotes: string, window: string, minimize: string, zoom: string, nextTab: string, previousTab: string, 
/**
 * Nine entries, already numbered — the numbering is wording, and wording is the catalogue's.
 */
selectTabs: Array<string>, };
