// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Act } from "./Act";

/**
 * Work the agent started and walked away from, still running after its turn closed.
 *
 * **"Nothing outstanding" answers a different question than "nothing is happening".** `Stop` means
 * the agent has replied, not that the machine is idle: a build started in the background runs on,
 * and the panel said the session was quiet through all of it. Reported while a DMG was compiling.
 *
 * Kept apart from [`Standing`] on purpose. That says whether the agent owes *you* something; this
 * says whether the machine is busy. Folding a background build into "working" would put back
 * exactly the inferred state that was cut out of it — the agent really has finished.
 */
export type Background = { 
/**
 * What the command was, as the classifier read it — `build`, `verify`, `ship`.
 */
act: Act, refinement: string | null, 
/**
 * Seconds since it was started.
 */
seconds: bigint, 
/**
 * It reported a non-zero exit while nobody was looking.
 *
 * The other half this pairing buys, and nothing reads it today: a background run that *failed*
 * after the agent went idle is invisible in every other surface.
 */
failed: boolean, };
