// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Build identity: SemVer version, channel (dev/release), and the exact commit it was built from
 * (ADR-CORE-024). Rendered in the title bar, status bar and About dialog.
 */
export type BuildInfo = { 
/**
 * SemVer version, from `package.json` via `CARGO_PKG_VERSION`.
 */
version: string, 
/**
 * Build channel: `"dev"` for debug builds, `"release"` otherwise (ADR-CORE-024).
 */
channel: string, 
/**
 * Whether this is a debug build (`cfg!(debug_assertions)`).
 */
debug: boolean, 
/**
 * Short git commit SHA the binary was built from (set by `build.rs`).
 */
git_sha: string, 
/**
 * Whether the working tree was dirty at build time.
 */
git_dirty: boolean, 
/**
 * Commit date of `git_sha` (ISO-8601) — answers "what's in this build".
 */
commit_date: string, };
