// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChainLink } from "./ChainLink";
import type { PlanStep } from "./PlanStep";
import type { Round } from "./Round";
import type { Standing } from "./Standing";

/**
 * Everything the tool needs for one tab.
 */
export type Chain = { 
/**
 * Newest last, exactly as the work happened.
 */
links: Array<ChainLink>, 
/**
 * The agent's plan, in the order it created it. Empty when it kept none.
 */
plan: Array<PlanStep>, 
/**
 * True when a plan existed and every step of it finished. **Distinct from an empty plan**: the
 * task store is cleared the moment nothing is open, so "finished" and "never had one" look
 * identical there. The transcript still holds the history, which is what tells them apart.
 */
plan_done: boolean, 
/**
 * What is expected next, from this session's own edge frequencies. An observation, never a
 * plan — the interface draws it differently for that reason.
 */
expected: Array<Round>, 
/**
 * Seconds since the first step of the session.
 */
elapsed: bigint, 
/**
 * Seconds since the **last** step — how long nothing has happened.
 *
 * **The chain has no other way to know the present.** It reads a file and would otherwise treat
 * the end of it as "now": an agent that stopped an hour ago still showed a link as running and
 * three more as expected, while nobody had asked it for anything. That is the same failure
 * `rule:attention-signals` records — a state that does not age becomes a lie, and the lie looks
 * exactly like information.
 */
idle: bigint, 
/**
 * What the agent is doing right now — the question the tool exists to answer.
 */
standing: Standing, 
/**
 * What it is waiting for, when it is waiting. The harness's own words, because a request names
 * what it wants and nothing we could write would be more accurate.
 */
waiting_for: string | null, 
/**
 * Tool calls seen, and how many were understood. A shorter chain and a genuinely shorter chain
 * look identical, so the reader reports its own coverage instead of going quiet (ADR-PROJ-005).
 */
steps_seen: number, steps_understood: number, 
/**
 * The Claude home this was read from — shown, because several can be in use and a wrong
 * attribution renders another account's work in this tab.
 */
home: string, session_id: string | null, 
/**
 * The harness version the transcript was written by. When it is one this reader was never
 * verified against, the tool says it is on unproven ground rather than quietly showing less.
 */
harness_version: string | null, };
