// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Act } from "./Act";
import type { Kind } from "./Kind";
import type { Outcome } from "./Outcome";
import type { Reach } from "./Reach";
import type { Round } from "./Round";

/**
 * One link of the chain, as the tool draws it.
 */
export type ChainLink = { act: Act, refinement: string | null, 
/**
 * The command that produced it, as a person would write it down — what `work-levels.json` is
 * looked up by.
 */
signature: string | null, outcome: Outcome, kind: Kind, reach: Reach | null, 
/**
 * Seconds from the first to the last step folded into this link.
 */
seconds: bigint, 
/**
 * How many tool calls it took. Not shown as such; it is what `noise` is measured against.
 */
steps: number, 
/**
 * Probes folded into this link — reading a log after a test run belongs *inside* the test.
 */
noise: number, 
/**
 * Context compacts that fell inside this link. A seam rather than work: it is drawn **on** the
 * link instead of between two, because as a link of its own it broke every cycle it landed in —
 * and an agent repeating itself after losing its context is the case an iteration count exists
 * for.
 */
compacts: number, 
/**
 * `Some` when this link is a folded cycle: how many times it went round.
 */
iterations: number | null, 
/**
 * The distinct refinements seen inside a cycle. **The reading is opposite** depending on this:
 * 16 iterations over 16 files is a list being worked through, over 1 file it is stuck.
 */
rounds: Array<Round>, 
/**
 * True when the classification came from the built-in heuristic rather than a declaration.
 * The interface says so; a guess that looks like a fact is the defect `AgentTool` already
 * avoids for the context window.
 */
guessed: boolean, };
