// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChainLink } from "./ChainLink";
import type { PlanStep } from "./PlanStep";
import type { Round } from "./Round";

/**
 * Everything the tool needs for one tab.
 */
export type Chain = { 
/**
 * Newest last, exactly as the work happened.
 */
links: Array<ChainLink>, 
/**
 * The agent's plan, in the order it created it. Empty when it kept none.
 */
plan: Array<PlanStep>, 
/**
 * True when a plan existed and every step of it finished. **Distinct from an empty plan**: the
 * task store is cleared the moment nothing is open, so "finished" and "never had one" look
 * identical there. The transcript still holds the history, which is what tells them apart.
 */
plan_done: boolean, 
/**
 * What is expected next, from this session's own edge frequencies. An observation, never a
 * plan — the interface draws it differently for that reason.
 */
expected: Array<Round>, 
/**
 * Seconds since the first step of the session.
 */
elapsed: bigint, 
/**
 * Tool calls seen, and how many were understood. A shorter chain and a genuinely shorter chain
 * look identical, so the reader reports its own coverage instead of going quiet (ADR-PROJ-005).
 */
steps_seen: number, steps_understood: number, 
/**
 * The Claude home this was read from — shown, because several can be in use and a wrong
 * attribution renders another account's work in this tab.
 */
home: string, session_id: string | null, 
/**
 * The harness version the transcript was written by. When it is one this reader was never
 * verified against, the tool says it is on unproven ground rather than quietly showing less.
 */
harness_version: string | null, };
