// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One Claude home on this machine.
 */
export type ClaudeHome = { 
/**
 * Absolute path.
 */
path: string, 
/**
 * What it is called in the interface — the directory name, `.claude` being "the default one".
 */
name: string, 
/**
 * Whether it has been used for the project currently open.
 */
used_here: boolean, };
