// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the launcher ended up, and whether it will actually be found.
 */
export type CliInstall = { 
/**
 * The directory the scripts were written to.
 */
directory: string, 
/**
 * The names now available, in that directory.
 */
names: Array<string>, 
/**
 * Whether that directory is on `PATH`. When false, the caller must say so — a launcher that is
 * installed and not found is worse than one that was never installed.
 */
onPath: boolean, };
