// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One Docker container, as the tool draws it.
 */
export type ContainerInfo = { 
/**
 * Short form — twelve characters, which is what every docker command accepts.
 */
id: string, name: string, 
/**
 * `running`, `exited`, `created`, `paused`.
 */
state: string, 
/**
 * `Up 3 hours (healthy)` — verbatim, because the health verdict lives only here.
 */
status: string, image: string, 
/**
 * Only ports published to the host, deduplicated: `3000→80`.
 */
ports: Array<string>, 
/**
 * The compose project, when it belongs to one.
 */
project: string | null, };
