// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one running container is currently consuming.
 *
 * Separate from [`ContainerInfo`] because it costs something to obtain: `docker stats` samples
 * twice to compute a CPU delta and takes ~2 s regardless of how many containers there are (measured
 * on six). The listing is cheap and always available; this is only fetched while the tool is on
 * screen (`components/tools/DockerTool`).
 */
export type ContainerStats = { 
/**
 * Matches [`ContainerInfo::id`] — both are fetched with `--no-trunc`, or they would not join.
 */
id: string, 
/**
 * Percent of one core, as docker reports it: >100 on a container using several.
 */
cpu_percent: number, 
/**
 * Bytes in use, resolved from docker's human-readable form.
 */
mem_used: number, 
/**
 * The container's memory limit in bytes, or the host's total when it has none.
 */
mem_limit: number, 
/**
 * Percent of the limit above. Taken from docker rather than divided here, so the two agree.
 */
mem_percent: number, };
