// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A fatal error from the **UI runtime**, on its way into the durable on-device crash record
 * (ADR-CORE-037, ADR-APP-032).
 *
 * The webview is its own entry point: a Rust panic hook cannot see anything thrown inside it, so the
 * frontend hands its last-resort failures over the IPC boundary instead. Nothing here leaves the
 * device (rule:privacy) — it is written to `<app_data_dir>/crashes/` and to the log, and that is all.
 */
export type CrashReport = { 
/**
 * Where in the UI runtime it surfaced: `render`, `uncaught` or `unhandledrejection`.
 */
source: string, 
/**
 * The error's message. Never a secret or user content (rule:logging).
 */
message: string, 
/**
 * JS stack trace, when the thrown value carried one (a thrown string does not).
 */
stack: string | null, };
