// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in a directory, as the file browser draws it.
 */
export type DirEntry = { name: string, 
/**
 * Absolute, so opening it needs no reassembly on the other side.
 */
path: string, directory: boolean, 
/**
 * Marked rather than followed: a link to a folder stays a link until the user opens it.
 */
symlink: boolean, 
/**
 * Bytes, for a file. `None` for a directory, whose byte count tells a reader nothing.
 */
size: bigint | null, 
/**
 * Starts with a dot. The frontend decides whether to show it; the backend always lists it.
 */
hidden: boolean, };
