// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirEntry } from "./DirEntry";

/**
 * One directory's entries, and whether there were more than the cap allows.
 */
export type DirListing = { entries: Array<DirEntry>, 
/**
 * True when the listing was capped. Surfaced, never silent — a truncation nobody mentions is a
 * lie about what is on disk.
 */
truncated: boolean, };
