// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaudeHome } from "./ClaudeHome";

/**
 * How a project is currently pointed at a Claude account, and what the machine can do about it.
 */
export type EnvironmentStatus = { 
/**
 * Every home found under the user's home directory.
 */
homes: Array<ClaudeHome>, 
/**
 * The home this project's `.envrc` declares, if any.
 */
declared: string | null, 
/**
 * Whether there is an `.envrc` at all, anywhere up the tree.
 */
has_envrc: boolean, direnv_installed: boolean, 
/**
 * Whether direnv would actually load this project's `.envrc` as it stands.
 */
direnv_allowed: boolean, };
