// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the file viewer can make of a file: text, a picture, or a named refusal.
 *
 * **Three states on the wire, so the panel never has to read an error message to find out.** The
 * viewer had two — text, or an error string rendered raw — so opening a PNG produced
 * *"…/shot.png is not a text file"* on screen: true, addressed to nobody, and silent about what to
 * do instead. A file this panel cannot draw is a **state**, and it is carried as one.
 */
export type FilePreviewDto = { "kind": "text", text: string, truncated: boolean, } | { "kind": "image", bytes: Array<number>, mime: string, } | { "kind": "unsupported", 
/**
 * `binary` or `image_too_large`. A key rather than a sentence: the wording is the
 * frontend's, in the user's language (rule:i18n).
 */
reason: string, size: bigint, };
