// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One path the working tree or index disagrees with (ADR-PROJ-001, Git tool).
 */
export type GitChange = { 
/**
 * Path relative to the repository root, as git itself reports it.
 */
path: string, 
/**
 * `modified` | `added` | `deleted` | `renamed` | `untracked` | `conflicted`.
 */
status: string, 
/**
 * Whether the change is in the index (staged) rather than only in the working tree.
 */
staged: boolean, };
