// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One commit in the branch history.
 */
export type GitCommit = { sha: string, 
/**
 * Abbreviated sha, for display.
 */
short_sha: string, 
/**
 * First line of the message.
 */
summary: string, author: string, 
/**
 * Commit time, ISO-8601.
 */
when: string, 
/**
 * Parent shas. Two or more means a merge — which is what the lane drawing is derived from.
 */
parents: Array<string>, 
/**
 * Branch and tag names pointing at this commit, already shortened.
 */
refs: Array<string>, };
