// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitFileStat } from "./GitFileStat";

/**
 * Everything about one commit — the whole message, not the summary the graph shows.
 */
export type GitCommitDetail = { sha: string, short_sha: string, 
/**
 * First line of the message.
 */
summary: string, 
/**
 * Everything after the first line, with the blank separator removed. Empty when there is none.
 */
body: string, author_name: string, author_email: string, 
/**
 * RFC 3339, so the frontend formats it in the user's own locale rather than being handed a
 * pre-formatted string it cannot re-render.
 */
authored_at: string, parents: Array<string>, refs: Array<string>, files: Array<GitFileStat>, };
