// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitHunk } from "./GitHunk";

/**
 * What changed in one file, ready to draw.
 */
export type GitDiff = { path: string, 
/**
 * Where the file was before a rename, when it was renamed.
 */
old_path: string | null, 
/**
 * Same vocabulary as `GitChange::status`.
 */
status: string, 
/**
 * True when this is the staged side of the change rather than the working-tree side.
 */
staged: boolean, 
/**
 * No hunks are produced for a binary blob — there is nothing a reader could do with them.
 */
binary: boolean, hunks: Array<GitHunk>, added: number, removed: number, };
