// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line of a diff, with both sides' line numbers already worked out.
 *
 * `kind` is `context`, `added` or `removed`. A string rather than an enum because the frontend
 * switches on it to pick a colour and nothing else — and a `#[serde(rename_all)]` enum would arrive
 * as exactly this string anyway (the same shape `GitChange::status` already uses).
 */
export type GitDiffLine = { kind: string, 
/**
 * Line number on the old side, absent for an added line.
 */
old_line: number | null, 
/**
 * Line number on the new side, absent for a removed line.
 */
new_line: number | null, 
/**
 * The line itself, without its trailing newline.
 */
text: string, };
