// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file's line counts inside a commit, for the file list under a commit message.
 */
export type GitFileStat = { path: string, old_path: string | null, status: string, added: number, removed: number, binary: boolean, };
