// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitDiffLine } from "./GitDiffLine";

/**
 * A run of changed lines with its surrounding context.
 */
export type GitHunk = { 
/**
 * The familiar `@@ -a,b +c,d @@`, produced here so the UI does not have to assemble one.
 */
header: string, old_start: number, new_start: number, lines: Array<GitDiffLine>, };
