// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitChange } from "./GitChange";
import type { GitCommit } from "./GitCommit";

/**
 * Everything the Git tool shows for one repository, read in a single pass.
 *
 * One DTO rather than four commands: the tool always renders all of it together, and four round
 * trips would let the branch, the file list and the history disagree with each other on screen.
 */
export type GitSnapshot = { 
/**
 * Absolute path of the repository's working-tree root.
 */
root: string, 
/**
 * The `origin` remote's URL, or `null` for a purely local repository.
 *
 * Carried because it is what identifies a PROJECT: the notes tool keys a project's folder off
 * it, so the same repository is the same folder on every machine however differently it happens
 * to be checked out (ADR-PROJ-004). The path alone cannot do that.
 */
remote: string | null, 
/**
 * Current branch, or `null` when HEAD is detached or unborn.
 */
branch: string | null, 
/**
 * Whether HEAD points at a commit rather than a branch.
 */
detached: boolean, 
/**
 * Abbreviated sha of HEAD, or `null` in a repository with no commits yet.
 */
head: string | null, 
/**
 * Commits ahead of / behind the upstream branch. Both `0` when there is no upstream.
 */
ahead: number, behind: number, changes: Array<GitChange>, commits: Array<GitCommit>, };
