// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of thing a step is, beyond its act.
 */
export type Kind = "normal" | "delegated" | "halt" | "bookkeeping";
