// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One captured log record, sent to the UI live and kept in the ring buffer.
 */
export type LogRecord = { 
/**
 * ISO-8601 UTC timestamp (UI localises).
 */
ts: string, 
/**
 * ERROR | WARN | INFO | DEBUG | TRACE
 */
level: string, 
/**
 * The `tracing` target (module path) that emitted the event.
 */
target: string, 
/**
 * The event's primary human-readable message.
 */
message: string, 
/**
 * JSON object of the event's structured fields.
 */
fields: string, };
