// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the notes sync is doing, and what it last said.
 *
 * `last_error` is git's own message, verbatim: "Permission denied (publickey)" is actionable where
 * "sync failed" is not, and a passphrased key that is not in the agent is the commonest way for this
 * to never work (ADR-PROJ-004).
 */
export type NotesStatus = { 
/**
 * Whether a clone exists on disk yet.
 */
connected: boolean, 
/**
 * The configured remote, or empty for local-only — in which case nothing leaves the device.
 */
remote: string, branch: string, sync: boolean, 
/**
 * Where the clone is. Shown, because a directory you cannot find is one you cannot back up.
 */
path: string, 
/**
 * Whether `git` was found at all. Missing git is a state, not a crash: everything except sync
 * keeps working.
 */
git_available: boolean, 
/**
 * Unix seconds of the last successful sync, if there has been one this run.
 */
last_sync: bigint | null, 
/**
 * git's own error from the last attempt, if it failed.
 */
last_error: string | null, 
/**
 * Commits made here that the remote does not have. **git already knows this** — asked for
 * against the local `origin/<branch>` ref, so reading it costs no network.
 */
ahead: number, 
/**
 * Edits on disk that are not even committed yet. Together with `ahead`, the honest answer to
 * "is what I just wrote anywhere but here?" — which a "last synced 14:02" cannot give.
 */
dirty: boolean, };
