// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An image in the repository that no note refers to any more.
 */
export type NoteOrphan = { 
/**
 * `<project>/assets/<file>` — what `notes_clean` takes back.
 */
key: string, bytes: number, };
