// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What became of one file an import was pointed at.
 */
export type NoteImportEntry = { 
/**
 * The file, as the user would recognise it in the dialog they picked it from.
 */
file: string, 
/**
 * The topic it became, or absent when nothing was written.
 */
topic: string | null, 
/**
 * How many images were copied in with it.
 */
images: number, 
/**
 * Everything deliberately not done, in words the user can act on — a picture that lay outside
 * the note's own folder, a topic that was already taken. **Reported, never swallowed**: an
 * import that quietly did less than it appeared to is indistinguishable from a broken one.
 */
skipped: Array<string>, };
