// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One search hit across the notes.
 */
export type NoteHit = { project: string, topic: string, line: string, 
/**
 * Byte offset of the line, so the view can open at it.
 */
offset: number, };
