// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One note file: where it lives and what is in it.
 *
 * Delivered in bulk (`notes_tree`), because one round trip per file — each on Tauri's main thread —
 * is what made opening the tool a visible wait.
 */
export type NoteFile = { project: string, topic: string, 
/**
 * The note's markdown. **Empty by design** in `notes_index`, which names files for a menu.
 */
text: string, };
