// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteImportEntry } from "./NoteImportEntry";

/**
 * The result of one import, one entry per file.
 */
export type NoteImportReport = { 
/**
 * False when the user closed the picker without choosing — which is not an error and must not
 * be shown as one.
 */
picked: boolean, entries: Array<NoteImportEntry>, };
