// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One search hit across the notes.
 */
export type NoteHit = { project: string, topic: string, line: string, 
/**
 * Offset of the line, so the view can open at it — in **UTF-16 code units**, the unit the
 * caret on the other side counts in (`notes::offsets`).
 */
offset: number, };
