// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a link ended — inferred from what followed it, never from an exit code.
 *
 * **Measured twice, in two projects, with different tooling: 6 of 381 and 6 of 876 tool results
 * carry `is_error`.** Agents pipe test runs through `| tail -60`, so the status belongs to the pipe.
 * Parsing output for `FAILED`/`passed` would be framework-specific and would lie after the next
 * tool update. What followed does not lie: a verify followed by a build was red; a verify followed
 * by a ship was green.
 */
export type Outcome = "live" | "failed" | "done" | "unknown";
