// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One step of the agent's own plan, reconstructed from its task list.
 */
export type PlanStep = { id: string, subject: string, 
/**
 * `pending`, `in_progress`, `completed`.
 */
status: string, 
/**
 * Ids of steps that must finish first. Empty in every live file measured so far, so the UI must
 * not depend on it — but it is carried, because when it appears it is the causal chain.
 */
blocked_by: Array<string>, };
