// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One TCP port a tab's processes are listening on.
 */
export type PortInfo = { port: number, pid: number, command: string, 
/**
 * `*`, `127.0.0.1`, `[::1]` — the difference between reachable from the network and not.
 */
address: string, };
