// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One process under a terminal tab.
 */
export type ProcessInfo = { pid: number, parent: number, 
/**
 * How far below the tab's own shell this sits, so the view can indent without nesting the data.
 */
depth: number, 
/**
 * `ps` state letters — `R` running, `S` sleeping, `Z` a zombie nobody reaped.
 */
state: string, 
/**
 * How long it has been alive, as `ps` formats it (`01:23:45`, `2-04:00:00`).
 */
elapsed: string, 
/**
 * The whole command line, spaces included. `node` alone is not an answer.
 */
command: string, };
