// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a run reaches. Shown always, even when it cannot be interpreted — `verify e2e → dev-backend`
 * is informative with no configuration, and the day it reads `→ app.example.com` the difference is
 * visible without anybody having defined "live" (chain-tool.md §8).
 */
export type Reach = { 
/**
 * `local`, `dev`, `staging`, `prod`.
 */
target: string, 
/**
 * The host, cluster or container actually touched, when the declaration names one.
 */
host: string | null, 
/**
 * True when the declaration claimed something closer than the heuristic recognised. The UI
 * shows this as a contradiction rather than resolving it (ADR-PROJ-005 §4).
 */
disputed: boolean, };
