// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Act } from "./Act";

/**
 * One iteration inside a folded cycle.
 */
export type Round = { act: Act, refinement: string | null, };
