// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TmuxMode } from "./TmuxMode";

/**
 * Persisted user preferences. Stored as JSON under `<app_data_dir>/settings.json`.
 *
 * Every field carries a serde default so a settings file written by an older version — missing a
 * newer field — still loads (the missing field falls back to its default) rather than failing to
 * parse and silently discarding the user's other preferences.
 */
export type SettingsDto = { 
/**
 * WebView zoom factor applied to the whole UI (ADR-APP-021). Clamped to [0.7, 1.6].
 */
ui_scale: number, 
/**
 * Terminal text size in CSS pixels, **independent of `ui_scale`**.
 *
 * Its own setting because the two are different questions: how big the chrome is, and how much
 * output fits on screen. The frontend divides this by `ui_scale` before handing it to the
 * emulator, so the WebView zoom cannot drag it along.
 */
terminal_font_size: number, 
/**
 * Whether a new terminal joins tmux, and whether it may create a session (ADR-PROJ-001).
 */
tmux_mode: TmuxMode, 
/**
 * The session to attach. Empty means "whatever is running" for `attach`, and a default name for
 * `attach-or-create` — see `terminal::tmux`.
 */
tmux_session: string, 
/**
 * When true, closing the window hides the app to a system-tray icon instead of quitting, so it
 * keeps running in the background (ADR-APP-021). Default `false` — a fresh app is a normal window.
 */
minimize_to_tray: boolean, };
