// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persisted user preferences. Stored as JSON under `<app_data_dir>/settings.json`.
 *
 * Every field carries a serde default so a settings file written by an older version — missing a
 * newer field — still loads (the missing field falls back to its default) rather than failing to
 * parse and silently discarding the user's other preferences.
 */
export type SettingsDto = { 
/**
 * WebView zoom factor applied to the whole UI (ADR-APP-021). Clamped to [0.7, 1.6].
 */
ui_scale: number, 
/**
 * When true, closing the window hides the app to a system-tray icon instead of quitting, so it
 * keeps running in the background (ADR-APP-021). Default `false` — a fresh app is a normal window.
 */
minimize_to_tray: boolean, };
