// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TmuxMode } from "./TmuxMode";

/**
 * Persisted user preferences. Stored as JSON under `<app_data_dir>/settings.json`.
 *
 * Every field carries a serde default so a settings file written by an older version — missing a
 * newer field — still loads (the missing field falls back to its default) rather than failing to
 * parse and silently discarding the user's other preferences.
 */
export type SettingsDto = { 
/**
 * WebView zoom factor applied to the whole UI (ADR-APP-021). Clamped to [0.7, 1.6].
 */
ui_scale: number, 
/**
 * Terminal text size in CSS pixels, **independent of `ui_scale`**.
 *
 * Its own setting because the two are different questions: how big the chrome is, and how much
 * output fits on screen. The frontend divides this by `ui_scale` before handing it to the
 * emulator, so the WebView zoom cannot drag it along.
 */
terminal_font_size: number, 
/**
 * The colour scheme a terminal uses, by id. Empty means the built-in HUD palette.
 */
terminal_theme: string, 
/**
 * The scheme a DIFF is drawn in. Empty means "whatever the tab's terminal uses" — the common
 * case, and the one that needs no configuring at all.
 */
diff_theme: string, 
/**
 * The scheme a COMMIT is drawn in. Empty means "the same as a diff".
 */
commit_theme: string, 
/**
 * The font family a terminal renders in. Empty means the app's own default stack.
 *
 * Stored as a NAME rather than a validated choice: a WebView cannot enumerate system fonts, so
 * there is no authoritative list to check against — the frontend offers what it could detect and
 * accepts anything typed. A name that is not installed falls back to the default stack, which is
 * what the CSS font stack does anyway.
 */
terminal_font: string, 
/**
 * Refresh the ahead/behind counts against the remote while the Git tool is open.
 *
 * The one outbound connection this app makes (ADR-PROJ-002), and switchable because of that: it
 * goes to a remote the user configured, carries nothing of ours, and cannot touch the working
 * tree — but it is still traffic nobody asked for on the day they opened the app.
 */
git_auto_fetch: boolean, 
/**
 * Which language the interface is in — `"en"` or `"de"`.
 *
 * Stored as a plain string rather than an enum, and the frontend decides what it means. The
 * backend has no messages of its own to translate: everything it produces is either a
 * diagnostic for the log (never translated — it is read by whoever is debugging, alongside
 * English tooling output) or an error the frontend renders. Making this an enum here would put
 * the list of shipped languages in a second place, so adding one would mean a Rust change and a
 * regenerated binding for a value the backend never inspects.
 *
 * Empty means "not chosen", which the frontend reads as English (ADR-PROJ-003).
 */
language: string, 
/**
 * Copy to the clipboard as soon as something is selected, the way many terminals do.
 *
 * Off by default, and deliberately so: it silently replaces whatever the user had copied, which
 * is a surprise the first time it costs someone a paste they were about to make.
 */
copy_on_select: boolean, 
/**
 * Which shell a new terminal starts, as an absolute path. Empty means the user's own `$SHELL`.
 *
 * Only a path the backend itself offered is ever accepted or acted on — see `terminal::shells`.
 * This is a *selection*, not a command line: the webview must not be able to name the program a
 * terminal runs (ADR-PROJ-001 §5).
 */
terminal_shell: string, 
/**
 * Whether a new terminal joins tmux, and whether it may create a session (ADR-PROJ-001).
 */
tmux_mode: TmuxMode, 
/**
 * The session to attach. Empty means "whatever is running" for `attach`, and a default name for
 * `attach-or-create` — see `terminal::tmux`.
 */
tmux_session: string, 
/**
 * When true, closing the window hides the app to a system-tray icon instead of quitting, so it
 * keeps running in the background (ADR-APP-021). Default `false` — a fresh app is a normal window.
 */
minimize_to_tray: boolean, };
