// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A shell this machine offers, as presented in Settings.
 *
 * The list is produced by the backend from what the operating system declares (`/etc/shells`, the
 * known Windows interpreters) plus the user's own `$SHELL`. The frontend picks *from* it; it never
 * composes a path of its own, and a value that is not on the list is refused (`terminal::shells`).
 */
export type ShellInfo = { 
/**
 * Absolute path to the interpreter.
 */
path: string, 
/**
 * What to call it — the file name, which is how people say it (`zsh`, `fish`).
 */
name: string, 
/**
 * True for the shell the user's account is configured with.
 */
is_default: boolean, };
