// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the agent is doing, when it is not doing anything.
 *
 * **There are exactly two ways for a chain to be quiet, and conflating them is the difference
 * between a useful panel and a decorative one** — the maintainer put it plainly: either nothing is
 * outstanding, or it is waiting for a person. "Quiet" alone leaves the reader to open the terminal
 * and find out, which is the work the panel exists to save.
 *
 * The distinction is not inferred from the transcript, which cannot express it: an agent waiting on
 * a permission prompt and one that finished write exactly the same thing — nothing. It comes from
 * the hook events (`agent::hooks`), which already separate a request that blocks from a turn that
 * ended, and which this app already installs for the attention bell (ADR-CORE-005: one source).
 */
export type Standing = "working" | "waiting" | "idle";
