// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The three numbers `uptime` prints: load over one, five and fifteen minutes.
 */
export type SystemLoad = { one: number, five: number, fifteen: number, 
/**
 * How many logical cores there are, so a caller can say whether that load is a lot.
 *
 * A load of 8 is idle on a 16-core machine and desperate on a 4-core one. Sending the number
 * with it is what lets the interface colour it honestly instead of guessing a threshold.
 */
cores: number, };
