// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A terminal session ended by itself — the user typed `exit`, or the shell died (ADR-PROJ-001).
 *
 * Closing a tab is the other direction and needs no event: the frontend already knows.
 */
export type TerminalExit = { 
/**
 * The session that ended.
 */
id: number, 
/**
 * Its exit code, or `null` when the status could not be read at all.
 */
code: number | null, };
