// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A terminal colour scheme — imported from iTerm2, or edited here.
 *
 * **Every colour is optional, on purpose.** Colour has one home in this project and it is the
 * frontend (`globals.css` + `palette.ts`, rule:theming); the backend storing a full palette would be
 * a second source for the same fact. A scheme carries only what it actually defines, and the
 * frontend fills the rest from the HUD palette — which is also what a user expects from a scheme
 * that never mentioned a cursor colour.
 */
export type TerminalTheme = { 
/**
 * Filesystem-safe id, derived from the name by the backend. Never chosen by a caller: it decides
 * a filename.
 */
id: string, name: string, 
/**
 * The 16 ANSI colours, in order. Always 16 entries; an undefined one is `null`.
 */
ansi: Array<string | null>, background: string | null, foreground: string | null, cursor: string | null, 
/**
 * The colour of the character *under* the cursor.
 */
cursor_accent: string | null, selection: string | null, selection_foreground: string | null, };
