// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a freshly opened session turned out to be.
 *
 * The id alone was enough while every terminal was a shell. It is not any more: a tab needs to know
 * which tmux session it landed on, or a restart cannot return it to the same work.
 */
export type TerminalOpened = { id: number, 
/**
 * The tmux session this attached to, or `null` for a plain shell.
 */
tmux_session: string | null, };
