// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A terminal session ended by itself — the user typed `exit`, or the shell died (ADR-PROJ-001).
 *
 * Closing a tab is the other direction and needs no event: the frontend already knows.
 */
export type TerminalExit = { 
/**
 * The session that ended.
 */
id: number, 
/**
 * Its exit code, or `null` when the status could not be read at all.
 */
code: number | null, 
/**
 * True when the session was a tmux CLIENT rather than a shell.
 *
 * The distinction is what tells a detach apart from a shell that exited. Detaching ends the
 * client, not the work: the tmux session is still there, and the user asked to be back in a
 * terminal — not to lose the tab.
 */
tmux_client: boolean, };
