// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortInfo } from "./PortInfo";
import type { ProcessInfo } from "./ProcessInfo";

/**
 * What a terminal tab is running, and what it has open.
 */
export type TerminalActivity = { processes: Array<ProcessInfo>, ports: Array<PortInfo>, 
/**
 * True when the roots came from tmux rather than from the tab's own child — the tree then shows
 * the whole session, which is what the user means by "what is running here".
 */
via_tmux: boolean, };
