// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a session is doing right now, as far as the backend can tell.
 *
 * Only tmux sessions have anything to report here: outside tmux the shell's own OSC 133 sequences
 * reach the emulator directly and are read there, instantly and with an exit status. Inside tmux
 * they are swallowed (measured), so the busy state is polled from `#{pane_current_command}` instead —
 * which says *whether* something is running, never how it ended.
 */
export type TerminalStatus = { 
/**
 * Whether the AI harness in this directory is mid-turn, or `None` when there is no agent here.
 *
 * **This overrides `busy` when it is set**, and that is the whole reason it exists. A harness is
 * a command that runs for hours, so `busy` — "the pane is running something other than the
 * shell" — answers *yes* from the moment it starts until it exits. Correct, and useless: it says
 * a program is open, not that it is doing something for you. Turn boundaries are the only signal
 * that tells those apart (`hooks::working_now`).
 */
agent_turn: boolean | null, 
/**
 * Where the session's shell is, when tmux can be asked.
 */
cwd: string | null, 
/**
 * The command tmux says is running, or `null` outside tmux.
 */
command: string | null, 
/**
 * The tmux session this tab is in, whoever started it.
 *
 * Separate from what `terminal_open` returned, because it answers a different question: that one
 * is "which session did WE join", this one is "which session is this terminal in right now" —
 * and a user who typed `tmux` themselves is only visible in the second.
 */
session: string | null, 
/**
 * True when that command is something other than the shell itself.
 */
busy: boolean, };
