// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A named set of overrides for what a terminal tab starts as.
 *
 * **Every field is an override, and Settings holds the defaults.** A profile that sets only a theme
 * takes its shell and its tmux behaviour from Settings, and changing Settings changes it — there is
 * no separate "default profile" document to keep in step (ADR-CORE-005).
 *
 * A profile is what `terminal_open` names, and it is a *reference*: the backend turns it into a
 * program. The webview never names one (ADR-PROJ-001 §5).
 */
export type TerminalProfile = { 
/**
 * Filesystem-safe id, derived from the name by the backend. Never chosen by a caller.
 */
id: string, name: string, 
/**
 * Absolute path to a shell, checked against the list this machine offers — a profile must not be
 * a way around the check Settings makes.
 */
shell: string | null, 
/**
 * Where a terminal opened with this profile starts.
 */
cwd: string | null, 
/**
 * A colour scheme id, as `TerminalTheme::id`.
 */
theme: string | null, };
