// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a session is doing right now, as far as the backend can tell.
 *
 * Only tmux sessions have anything to report here: outside tmux the shell's own OSC 133 sequences
 * reach the emulator directly and are read there, instantly and with an exit status. Inside tmux
 * they are swallowed (measured), so the busy state is polled from `#{pane_current_command}` instead —
 * which says *whether* something is running, never how it ended.
 */
export type TerminalStatus = { 
/**
 * Where the session's shell is, when tmux can be asked.
 */
cwd: string | null, 
/**
 * The command tmux says is running, or `null` outside tmux.
 */
command: string | null, 
/**
 * True when that command is something other than the shell itself.
 */
busy: boolean, };
