// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file's contents for the inline viewer.
 */
export type TextFileDto = { text: string, 
/**
 * True when the file was longer than the viewer's cap and only its head is here — said out loud
 * in the panel, because a file that silently stops is read as a file that ends there.
 */
truncated: boolean, };
