// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a new terminal does about tmux.
 *
 * Three states rather than a boolean, because "join a session if one is running, otherwise just give
 * me a shell" and "always have a session, creating one if needed" are different wishes, and a toggle
 * can only express one of them.
 */
export type TmuxMode = "off" | "attach" | "attach-or-create";
