// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageLimit } from "./UsageLimit";

/**
 * How much of the subscription is used up, as Claude Code reports it.
 */
export type UsageSummary = { 
/**
 * A list rather than named fields: the categories are Anthropic's to change, and a struct with
 * three of them would silently drop a fourth.
 */
limits: Array<UsageLimit>, requests_24h: number | null, sessions_24h: number | null, };
