// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One usage limit and how full it is.
 */
export type UsageLimit = { 
/**
 * `Current session`, `Current week (all models)` — Anthropic's wording, kept verbatim.
 */
label: string, percent: number, 
/**
 * When it resets, as reported. Absent for a limit that does not say.
 */
resets: string | null, };
