// Shared governance library: parse ADR/rule/memory front-matter and (re)generate all indexes.
// Single source of truth for sync-index.mjs and check-index.mjs (ADR-CORE-005, ADR-CORE-007).
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
export const ADR_DIR = path.join(ROOT, "docs", "adr");
export const RULES_DIR = path.join(ROOT, ".claude", "rules");
export const MEMORY_DIR = path.join(ROOT, ".claude", "memory");
// Project-owned governance line (ADR-CORE-030): indexed + validated by the same scripts, but NOT part of
// the pinned core manifest, so a project owns and freely changes these.
export const RULES_PROJECT_DIR = path.join(RULES_DIR, "project");
export const ADR_PROJECT_DIR = path.join(ADR_DIR, "project");
export const BLUEPRINT = path.join(ROOT, "docs", "agent-governance-blueprint.md");

export const LOAD_TIERS = ["core", "conditional", "archival"];
export const ADR_STATUSES = ["proposed", "accepted", "superseded", "deprecated"];
export const TLDR_MAX = 160;

const GENERATED_NOTICE = "<!-- GENERATED by scripts/sync-index.mjs — do not edit by hand. -->";

/** List `*.md` files in a directory, excluding the given basenames. Returns absolute paths, sorted. */
export function listMarkdown(dir, exclude = []) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".md") && !exclude.includes(f))
    .sort()
    .map((f) => path.join(dir, f));
}

/** Parse one governance document. Returns { file, rel, data, body, hash }.
 *
 * Line endings are normalised BEFORE hashing, exactly as `hashFile` does in governance-core. Without it
 * the content hash is platform-dependent: a Windows working tree holds CRLF, git stores LF, a Linux CI
 * runner checks out LF — so the same document hashes differently there, `docs/adr/manifest.json`
 * regenerates differently, and the staleness gate reports it stale. That is not a flaky test, it is a gate
 * that is green on the maintainer's machine and red in CI **forever**, and no local run can ever see it
 * (rule:cross-platform). */
export function parseDoc(file) {
  const raw = fs.readFileSync(file, "utf8").replace(/\r\n/g, "\n");
  const { data, content } = matter(raw);
  const hash = crypto
    .createHash("sha256")
    .update(JSON.stringify(data) + "\n" + content.trim())
    .digest("hex")
    .slice(0, 16);
  // Normalise to POSIX-style forward slashes so the generated manifest is byte-identical across
  // OSes. `path.relative` yields backslashes on Windows, which made `manifest.json` flip-flop and
  // fail the staleness gate every time the repo was synced between macOS and Windows.
  const rel = path.relative(ROOT, file).split(path.sep).join("/");
  return { file, rel, data, body: content, hash };
}

/** Validate common front-matter. Returns an array of error strings (empty = ok). */
export function validateCommon(doc, { kind }) {
  const e = [];
  const d = doc.data;
  for (const field of ["id", "title", "tldr", "scope", "load"]) {
    if (d[field] === undefined || d[field] === null || d[field] === "") {
      e.push(`${doc.rel}: missing front-matter field '${field}'`);
    }
  }
  if (typeof d.tldr === "string" && d.tldr.length > TLDR_MAX) {
    e.push(`${doc.rel}: tldr is ${d.tldr.length} chars (max ${TLDR_MAX})`);
  }
  if (d.load && !LOAD_TIERS.includes(d.load)) {
    e.push(`${doc.rel}: invalid load '${d.load}' (expected ${LOAD_TIERS.join("|")})`);
  }
  // Reachability (rule:knowledge-handover, ADR-CORE-006): a `conditional` document is loaded ONLY when its
  // triggers or applies-to match the task. Declaring neither makes it unreachable — the knowledge is in
  // the repo but never reaches the agent who needs it, which is the same as not writing it down.
  if (d.load === "conditional") {
    const triggers = Array.isArray(d.triggers) ? d.triggers : [];
    const appliesTo = Array.isArray(d["applies-to"]) ? d["applies-to"] : [];
    if (!triggers.length && !appliesTo.length) {
      e.push(
        `${doc.rel}: unreachable — a 'conditional' document must declare 'triggers' or 'applies-to', otherwise no agent ever loads it.`,
      );
    }
  }
  if (kind === "adr") {
    if (!d.status || !ADR_STATUSES.includes(d.status)) {
      e.push(`${doc.rel}: invalid/missing status (expected ${ADR_STATUSES.join("|")})`);
    }
  }
  // `supersedes` is how a document retires another — including one in a layer it may not edit
  // (ADR-CORE-035). It is available to ADRs, rules and memory alike, so it is validated here, once.
  if (d.supersedes !== undefined) {
    if (!Array.isArray(d.supersedes) || d.supersedes.some((s) => typeof s !== "string")) {
      e.push(`${doc.rel}: 'supersedes' must be a list of document ids, e.g. [ADR-APP-020]`);
    }
  }
  return e;
}

const tagLine = (doc, line) => ({ ...doc, line });

/**
 * An ADR id carries the layer that owns it: `ADR-CORE-004`, `ADR-APP-026`, `ADR-PROJ-105` (ADR-CORE-034).
 *
 * Number blocks (core 001–099, project 100–199, …) were the alternative, and they were already broken:
 * the app layer historically holds 001/020/021/023/025/026/031, all inside the core's block. A block is a
 * convention a human has to keep; a prefix is a property of the identifier — and it lets the gate check
 * that a document's id agrees with the layer that actually owns it, which a number never could.
 */
export const ADR_ID_RE = /^ADR-([A-Z][A-Z0-9]*(?:-[A-Z0-9]+)*)-(\d{3})$/;

/** The layer an ADR id claims: `ADR-APP-026` → "app". Null if the id is not well-formed. */
export function adrLayerOf(id) {
  const m = ADR_ID_RE.exec(String(id ?? ""));
  return m ? m[1].toLowerCase() : null;
}

/** The prefix a layer uses. The project layer is the one that is never published, hence the short form. */
export function prefixOfLayer(layer) {
  return layer === "project" ? "PROJ" : String(layer).toUpperCase();
}

/**
 * A migration briefing filename: `<layer>-NNN-<slug>.md` (ADR-CORE-038).
 *
 * A briefing carries no front-matter and no id, so the **filename is its identifier** — and it is also the
 * collision surface. Two layers that ship `docs/migrations/008-x.md` do not merely confuse a reader:
 * `detectCollisions` aborts the consumer's `governance:update` (scripts/governance-update.mjs), stopping it
 * from pulling anything at all until a published file is renamed.
 *
 * Number blocks (core 001–099, app 100–199, project 200+) were the previous answer. They were prose in a
 * README, checked by nothing — and an agent in the app layer, looking at a directory that stops at `007-`,
 * picks `008-` as the next free number without ever seeing the rule. Same failure as ADR-CORE-034, same fix:
 * put the layer in the identifier, where a gate can compare what the name CLAIMS against the layer that
 * actually owns the file. Numbering is then per-layer, independent, and unbounded.
 */
export const BRIEFING_NAME_RE = /^([a-z][a-z0-9]*)-(\d{3})-([a-z0-9]+(?:-[a-z0-9]+)*)\.md$/;

/** The layer a briefing filename claims: `core-001-x.md` → "core". Null if the name is not well-formed. */
export function briefingLayerOf(name) {
  const m = BRIEFING_NAME_RE.exec(String(name ?? ""));
  return m ? m[1] : null;
}

/**
 * The prefix a layer uses in a **filename** — lowercase, and `proj` for the project layer, exactly as its
 * ADR files are named (`proj-105-…md`). Kept apart from `prefixOfLayer` on purpose: comparing a filename
 * against an id's alphabet is how the ADR gate once fired on correct files and told the agent to rename
 * them to themselves.
 */
export function filePrefixOfLayer(layer) {
  return prefixOfLayer(layer).toLowerCase();
}

export function loadAdrs() {
  const load = (dir, line) =>
    listMarkdown(dir, ["README.md"])
      // Identify an ADR by its id, not by its filename: the filename now carries the layer prefix too
      // (`core-004-…md`), and a pattern match on `NNN-` would simply have stopped seeing them.
      .map((f) => tagLine(parseDoc(f), line))
      .filter((d) => String(d.data.id ?? "").startsWith("ADR-"))
      .sort(byId);
  // Core line first, then the project line (both indexed by the same generator).
  return [...load(ADR_DIR, "core"), ...load(ADR_PROJECT_DIR, "project")];
}
export function loadRules() {
  const core = listMarkdown(RULES_DIR, ["INDEX.md"]).map((f) => tagLine(parseDoc(f), "core"));
  const project = listMarkdown(RULES_PROJECT_DIR, ["README.md"]).map((f) =>
    tagLine(parseDoc(f), "project"),
  );
  return [...core.sort(byId), ...project.sort(byId)];
}
export function loadMemory() {
  return listMarkdown(MEMORY_DIR, ["README.md", "MEMORY.md"]).map(parseDoc).sort(byId);
}
function byId(a, b) {
  return String(a.data.id).localeCompare(String(b.data.id), "en", { numeric: true });
}

const esc = (s) => String(s ?? "").replace(/\|/g, "\\|");

/**
 * Who supersedes whom — derived from the `supersedes` list of every document, and from nothing else
 * (ADR-CORE-035).
 *
 * Supersession used to be declared in **both** documents: `status: superseded` + `superseded-by` in the
 * old one, `supersedes` in the new one. Across a layer boundary that procedure is not merely awkward, it
 * is **impossible**: the old document belongs to an upstream layer, is hash-pinned, and the drift-gate
 * refuses the edit. A consumer therefore had no legal way to say "this upstream decision does not apply
 * to me" — the one thing layers exist to permit. It worked around it by writing a parallel rule whose
 * first paragraph said "the pinned rule does not apply here"; every further consumer would have
 * reinvented that.
 *
 * So the declaration lives in the **superseding** document only. The old file is never touched; the
 * generated indexes carry the result. Direction is checked in `check-index.mjs`: a HIGHER layer may
 * supersede a lower one (a project may retire an app decision), never the reverse.
 *
 * Returns `Map<supersededId, supersedingDoc>`. Ids are namespaced (`ADR-…`, `rule:…`, `mem:…`), so one
 * map serves all three kinds.
 */
export function resolveSupersessions(docs) {
  const by = new Map();
  for (const d of docs) {
    const list = Array.isArray(d.data.supersedes) ? d.data.supersedes : [];
    for (const target of list) by.set(String(target), d);
  }
  return by;
}

/** A document's status after supersession is applied — the file's own `status` is only a starting point. */
export function effectiveStatus(doc, supersededBy) {
  return supersededBy.has(String(doc.data.id)) ? "superseded" : doc.data.status;
}

const supersederId = (doc, supersededBy) =>
  supersededBy.get(String(doc.data.id))?.data.id ?? doc.data["superseded-by"] ?? null;

/** docs/adr/manifest.json (machine index). */
export function genAdrManifest(adrs, supersededBy = new Map()) {
  const entries = adrs.map((d) => ({
    id: d.data.id,
    // The layer is not a separate fact to keep in sync — it is read straight off the id (ADR-CORE-034).
    layer: adrLayerOf(d.data.id),
    title: d.data.title,
    tldr: d.data.tldr,
    scope: d.data.scope,
    load: d.data.load,
    // Derived, not copied: a downstream layer can retire this ADR without ever touching its file.
    status: effectiveStatus(d, supersededBy),
    triggers: d.data.triggers ?? [],
    "applies-to": d.data["applies-to"] ?? [],
    supersededBy: supersederId(d, supersededBy),
    path: d.rel,
    hash: d.hash,
  }));
  return JSON.stringify({ generated: true, count: entries.length, adrs: entries }, null, 2) + "\n";
}

/** docs/adr/README.md (human index). */
export function genAdrReadme(adrs, supersededBy = new Map()) {
  const rows = adrs
    .map((d) => {
      const by = supersededBy.get(String(d.data.id));
      const status = by
        ? `superseded by ${by.data.id}`
        : effectiveStatus(d, supersededBy) +
          (d.data["superseded-by"] ? ` by ${d.data["superseded-by"]}` : "");
      return `| [${d.data.id}](${path.relative(ADR_DIR, d.file).split(path.sep).join("/")}) | ${adrLayerOf(d.data.id) ?? "?"} | ${esc(d.data.title)} | ${esc(d.data.tldr)} | ${esc(status)} | ${d.data.load} |`;
    })
    .join("\n");
  return `${GENERATED_NOTICE}

# Architecture Decision Records

Every agent MUST read the ADRs relevant to its task before changing code. ADRs document **why**
decisions were made. Loading follows the contract in \`.claude/rules/context-loading.md\` and ADR-CORE-006:
always read \`load: core\`; read \`conditional\` when scope/triggers match; read \`archival\` only on
demand.

This index and \`manifest.json\` are generated from the ADR front-matter by \`scripts/sync-index.mjs\`.
Run \`npm run governance:sync\` after adding or editing an ADR; \`npm run governance:check\` enforces it.

## Format

\`\`\`
# ADR-NNN: Title
- Status / Date / Metadata (scope, load, triggers, applies-to, supersedes)
- Context / Decision / Alternatives / Consequences / References
\`\`\`

## Index

The **Layer** column is read straight off the id (\`ADR-CORE-004\`, \`ADR-APP-026\`, \`ADR-PROJ-105\`) —
it is not a second fact that could drift. A document in a lower layer may never cite one in a higher
layer; \`governance:check\` rejects it (ADR-CORE-033, ADR-CORE-034).

**Status is derived** (ADR-CORE-035): an ADR reads \`superseded by X\` when **X** declares
\`supersedes: [it]\` — including when X sits in a higher layer. The superseded file itself is never
edited, which is what lets a project retire an upstream decision it does not follow.

| ADR | Layer | Title | TL;DR | Status | Load |
| --- | --- | --- | --- | --- | --- |
${rows}
`;
}

/** docs/adr/current/README.md (operational snapshot of accepted ADRs). */
export function genAdrCurrent(adrs, supersededBy = new Map()) {
  const accepted = adrs.filter((d) => effectiveStatus(d, supersededBy) === "accepted");
  const rows = accepted
    .map(
      (d) =>
        `| [${d.data.id}](../${path.relative(ADR_DIR, d.file).split(path.sep).join("/")}) | ${adrLayerOf(d.data.id) ?? "?"} | ${esc(d.data.title)} | ${d.data.load} |`,
    )
    .join("\n");
  return `${GENERATED_NOTICE}

# Current ADRs (accepted snapshot)

${accepted.length} accepted decisions. Superseded/deprecated ADRs are omitted here; see the full index
in [../README.md](../README.md).

| ADR | Layer | Title | Load |
| --- | --- | --- | --- |
${rows}
`;
}

/** .claude/rules/INDEX.md (rule TLDR bootstrap list). */
export function genRulesIndex(rules, supersededBy = new Map()) {
  const rows = rules
    .map((d) => {
      const by = supersededBy.get(String(d.data.id));
      // A superseded rule must not be loaded — saying so in the very column an agent reads to decide.
      const tldr = by
        ? `**SUPERSEDED by ${by.data.id} — do not load this rule.** ${d.data.tldr}`
        : d.data.tldr;
      const load = by ? "superseded" : d.data.load;
      return `| [${esc(d.data.id)}](${path.relative(RULES_DIR, d.file).split(path.sep).join("/")}) | ${esc(tldr)} | ${load} | ${(d.data.triggers ?? []).join(", ")} |`;
    })
    .join("\n");
  return `${GENERATED_NOTICE}

# Rules index

Generated from rule front-matter by \`scripts/sync-index.mjs\`. Always load \`core\` rules; load others
when their triggers/applies-to match (see \`context-loading.md\`).

A rule marked **superseded** was retired by another rule that declares \`supersedes\` (ADR-CORE-035) —
including one in a higher layer. **Do not load it**; load the rule named in its row instead. The retired
file is left untouched, which is how a project can decline a rule an upstream layer publishes.

| Rule | TL;DR | Load | Triggers |
| --- | --- | --- | --- |
${rows}
`;
}

/** .claude/memory/MEMORY.md (memory index).
 *
 * The line carries `triggers`/`applies-to` because for memory **this index is the only one there is**:
 * ADRs get `manifest.json`, rules get `INDEX.md`, and both publish those fields. A memory's line used to
 * stop at the tldr, so its triggers were visible nowhere but inside the file an agent would have to have
 * loaded already — while `validateCommon` demanded them of every `conditional` memory. A required field
 * with no reader is not a contract, it is a chore. Core memory is loaded unconditionally, so it has
 * nothing to match on and its line is left alone.
 */
export function genMemoryIndex(memos, supersededBy = new Map()) {
  const rows = memos
    .map((d) => {
      const by = supersededBy.get(String(d.data.id));
      const tldr = by
        ? `**SUPERSEDED by ${by.data.id} — do not load.** ${d.data.tldr}`
        : d.data.tldr;
      const match = [
        ["triggers", d.data.triggers ?? []],
        ["applies-to", d.data["applies-to"] ?? []],
      ]
        .filter(([, v]) => Array.isArray(v) && v.length)
        .map(([k, v]) => ` · ${k}: ${esc(v.join(", "))}`)
        .join("");
      return `- [${esc(d.data.title)}](${path.basename(d.rel)}) — ${esc(tldr)}${match}`;
    })
    .join("\n");
  return `${GENERATED_NOTICE}

# Memory index

Repo-resident agent memory (ADR-CORE-003). Generated by \`scripts/sync-index.mjs\`; see
[README.md](README.md) for what belongs here.

${rows}
`;
}

/** Replace the body between AUTO-GENERATED:<name> START/END markers. */
export function replaceMarkerBlock(text, name, body) {
  const start = new RegExp(`(<!-- AUTO-GENERATED:${name} START[^>]*-->)`);
  const end = new RegExp(`(<!-- AUTO-GENERATED:${name} END -->)`);
  const ms = text.match(start);
  const me = text.match(end);
  if (!ms || !me) throw new Error(`marker block '${name}' not found in blueprint`);
  const before = text.slice(0, ms.index + ms[0].length);
  const after = text.slice(me.index);
  return `${before}\n${body}\n${after}`;
}

/** Compact tables embedded into the blueprint Part A. */
export function genBlueprintAdrBlock(adrs) {
  const rows = adrs
    .map((d) => `| ${d.data.id} | ${esc(d.data.tldr)} | ${d.data.load} |`)
    .join("\n");
  return `\n| ADR | TL;DR | Load |\n| --- | --- | --- |\n${rows}\n`;
}
export function genBlueprintRulesBlock(rules) {
  const rows = rules
    .map((d) => `| ${esc(d.data.id)} | ${esc(d.data.tldr)} | ${d.data.load} |`)
    .join("\n");
  return `\n| Rule | TL;DR | Load |\n| --- | --- | --- |\n${rows}\n`;
}

/** Compute every generated artefact as { path, content }. Pure — no writes.
 *
 * The portable governance blueprint (`docs/agent-governance-blueprint.md`) is maintained in the
 * source repo this system was born in; downstream projects that adopt the system don't carry it.
 * If it's absent here, we simply skip its auto-generated index blocks. */
export function computeArtifacts() {
  const adrs = loadAdrs();
  const rules = loadRules();
  const memos = loadMemory();

  // One map across all three kinds: ids are namespaced, and a project rule may retire an app rule exactly
  // as a project ADR retires an app ADR (ADR-CORE-035).
  const supersededBy = resolveSupersessions([...adrs, ...rules, ...memos]);

  const artifacts = [
    { path: path.join(ADR_DIR, "manifest.json"), content: genAdrManifest(adrs, supersededBy) },
    { path: path.join(ADR_DIR, "README.md"), content: genAdrReadme(adrs, supersededBy) },
    {
      path: path.join(ADR_DIR, "current", "README.md"),
      content: genAdrCurrent(adrs, supersededBy),
    },
    { path: path.join(RULES_DIR, "INDEX.md"), content: genRulesIndex(rules, supersededBy) },
    { path: path.join(MEMORY_DIR, "MEMORY.md"), content: genMemoryIndex(memos, supersededBy) },
  ];

  if (fs.existsSync(BLUEPRINT)) {
    let blueprint = fs.readFileSync(BLUEPRINT, "utf8");
    blueprint = replaceMarkerBlock(blueprint, "adr-index", genBlueprintAdrBlock(adrs));
    blueprint = replaceMarkerBlock(blueprint, "rules-index", genBlueprintRulesBlock(rules));
    artifacts.push({ path: BLUEPRINT, content: blueprint });
  }

  return { adrs, rules, memos, supersededBy, artifacts };
}

/**
 * Collect the governance ids a document cites in its BODY — `ADR-NNN` and `rule:<slug>` — excluding its
 * own id. These bare citations are how the rules and ADRs actually reference each other in prose, so a
 * layer gate that only looked at markdown links (ADR-CORE-033) would miss most of the dependencies it exists
 * to police: `core-principles.md` cites ADR-APP-026 in plain text, not as a link.
 *
 * Front-matter is skipped on purpose: `id`, `supersedes` and `superseded-by` are metadata about the
 * document, not dependencies of it.
 */
export function collectIdRefs(file) {
  const { data, content } = matter(fs.readFileSync(file, "utf8"));
  const self = String(data.id ?? "");
  const found = new Set();

  // An id inside a code fence or a code span is an ILLUSTRATION, not a citation — the documents that
  // explain the id scheme are full of `ADR-APP-026`-style examples, and treating those as references
  // would make it impossible to document the scheme in the layer that defines it. Prose citations, which
  // is how these documents actually reference each other, are unaffected.
  const prose = content
    .replace(/```[\s\S]*?```/g, "")
    .replace(/~~~[\s\S]*?~~~/g, "")
    .replace(/`[^`\n]*`/g, "");
  for (const re of [
    // Both the layered form (ADR-CORE-004) and the bare legacy one (ADR-APP-026) are collected on purpose.
    // The legacy form resolves to nothing once the ids carry their layer, so the gate reports it as a
    // dead citation instead of leaving a stale reference silently pointing at a document that no longer
    // answers to that name (ADR-CORE-034).
    /\bADR-(?:[A-Z][A-Z0-9]*(?:-[A-Z0-9]+)*-)?\d{3}\b/g,
    /\brule:[a-z0-9][a-z0-9-]*/g,
  ]) {
    for (const m of prose.matchAll(re)) found.add(m[0]);
  }
  found.delete(self);
  return [...found];
}

/** Collect markdown links of the form [text](relative.md...) from a file, return absolute targets. */
export function collectLinks(file) {
  const text = fs.readFileSync(file, "utf8");
  const out = [];
  const re = /\]\(([^)]+\.md)(#[^)]*)?\)/g;
  let m;
  while ((m = re.exec(text)) !== null) {
    const target = m[1];
    if (/^https?:/.test(target)) continue;
    out.push({ target, abs: path.resolve(path.dirname(file), target) });
  }
  return out;
}
