// @vitest-environment node
// Tests for the version SSOT sync (ADR-CORE-024): package.json is authoritative and is written into BOTH
// src-tauri/Cargo.toml ([package] version) and src-tauri/Cargo.lock (the crate's own [[package]]
// entry). The lock is the part that used to be forgotten — a bumped Cargo.toml with a stale lock
// breaks every `--locked` build (clippy/test/CI) with "cannot update the lock file". Everything runs
// against a temp repo — never the real one.
import { describe, it, expect, beforeEach, afterEach } from "vitest";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {
  CARGO_LOCK,
  CARGO_TOML,
  crateNameOf,
  lockVersionOf,
  packageVersionOf,
  syncVersion,
  withLockVersion,
  withPackageVersion,
} from "./sync-version.mjs";

const CARGO_TOML_FIXTURE = `[package]
name = "saga_rust_template"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "2.11.2", features = ["tray-icon"] }
serde = "1.0.228"
`;

// A real lock starts with the lockfile-format key `version = 4` — it must never be mistaken for a
// package version. Two neighbour packages guard against a greedy match.
const CARGO_LOCK_FIXTURE = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "anyhow"
version = "1.0.100"

[[package]]
name = "saga_rust_template"
version = "0.1.0"
dependencies = [
 "anyhow",
 "tauri",
]

[[package]]
name = "zerocopy"
version = "0.1.0"
`;

let root;

/** Materialise a minimal repo (package.json + Cargo.toml + Cargo.lock) in a temp dir. */
function repo({
  pkgVersion = "0.2.0",
  cargoToml = CARGO_TOML_FIXTURE,
  cargoLock = CARGO_LOCK_FIXTURE,
} = {}) {
  fs.writeFileSync(
    path.join(root, "package.json"),
    JSON.stringify({ name: "app", version: pkgVersion }),
  );
  fs.mkdirSync(path.join(root, "src-tauri"), { recursive: true });
  if (cargoToml !== null) fs.writeFileSync(path.join(root, CARGO_TOML), cargoToml);
  if (cargoLock !== null) fs.writeFileSync(path.join(root, CARGO_LOCK), cargoLock);
}

const read = (rel) => fs.readFileSync(path.join(root, rel), "utf8");

beforeEach(() => {
  root = fs.mkdtempSync(path.join(os.tmpdir(), "sync-version-"));
});

afterEach(() => {
  fs.rmSync(root, { recursive: true, force: true });
});

describe("Cargo.toml", () => {
  it("reads the [package] version, never a dependency version", () => {
    expect(packageVersionOf(CARGO_TOML_FIXTURE)).toBe("0.1.0");
  });

  it("rewrites only the [package] version", () => {
    const out = withPackageVersion(CARGO_TOML_FIXTURE, "0.2.0");
    expect(packageVersionOf(out)).toBe("0.2.0");
    expect(out).toContain('tauri = { version = "2.11.2", features = ["tray-icon"] }');
    expect(out).toContain('serde = "1.0.228"');
  });

  it("reads the crate name", () => {
    expect(crateNameOf(CARGO_TOML_FIXTURE)).toBe("saga_rust_template");
  });
});

describe("Cargo.lock", () => {
  it("reads the crate's own [[package]] version", () => {
    expect(lockVersionOf(CARGO_LOCK_FIXTURE, "saga_rust_template")).toBe("0.1.0");
  });

  it("rewrites only the crate's entry — not its neighbours, not the lockfile format version", () => {
    const out = withLockVersion(CARGO_LOCK_FIXTURE, "saga_rust_template", "0.2.0");
    expect(lockVersionOf(out, "saga_rust_template")).toBe("0.2.0");
    expect(lockVersionOf(out, "anyhow")).toBe("1.0.100");
    expect(lockVersionOf(out, "zerocopy")).toBe("0.1.0");
    expect(out).toContain("\nversion = 4\n");
  });

  it("returns null when the crate has no entry", () => {
    expect(lockVersionOf(CARGO_LOCK_FIXTURE, "not_in_lock")).toBeNull();
  });
});

describe("syncVersion", () => {
  it("writes package.json's version into Cargo.toml and Cargo.lock", () => {
    repo({ pkgVersion: "0.2.0" });

    const result = syncVersion({ root });

    expect(result.version).toBe("0.2.0");
    expect(result.drift).toBe(false);
    expect(result.written).toEqual([CARGO_TOML, CARGO_LOCK]);
    expect(packageVersionOf(read(CARGO_TOML))).toBe("0.2.0");
    expect(lockVersionOf(read(CARGO_LOCK), "saga_rust_template")).toBe("0.2.0");
  });

  it("reports drift in Cargo.lock even when Cargo.toml is already in sync", () => {
    // The exact regression: an older `version` hook synced Cargo.toml only, so the lock kept the old
    // number and the next `--locked` build died. The gate must see it.
    repo({ pkgVersion: "0.2.0", cargoToml: withPackageVersion(CARGO_TOML_FIXTURE, "0.2.0") });

    const result = syncVersion({ root, check: true });

    expect(result.drift).toBe(true);
    expect(result.stale).toEqual([{ file: CARGO_LOCK, found: "0.1.0" }]);
    expect(lockVersionOf(read(CARGO_LOCK), "saga_rust_template")).toBe("0.1.0"); // --check never writes
  });

  it("is a no-op when both files already match", () => {
    repo({
      pkgVersion: "0.2.0",
      cargoToml: withPackageVersion(CARGO_TOML_FIXTURE, "0.2.0"),
      cargoLock: withLockVersion(CARGO_LOCK_FIXTURE, "saga_rust_template", "0.2.0"),
    });

    const result = syncVersion({ root, check: true });

    expect(result.drift).toBe(false);
    expect(result.written).toEqual([]);
  });

  it("fails loudly when the crate is missing from the lock", () => {
    repo({ cargoLock: '[[package]]\nname = "anyhow"\nversion = "1.0.100"\n' });

    expect(() => syncVersion({ root })).toThrow(/saga_rust_template/);
  });

  it("fails loudly when Cargo.toml has no [package] version", () => {
    repo({ cargoToml: '[package]\nname = "saga_rust_template"\nedition = "2021"\n' });

    expect(() => syncVersion({ root })).toThrow(/\[package\] version/);
  });

  it("skips the lock when the project has none yet (nothing built)", () => {
    repo({ cargoLock: null });

    const result = syncVersion({ root });

    expect(result.written).toEqual([CARGO_TOML]);
    expect(result.drift).toBe(false);
  });
});
