//! Teaching the user's shell to report where it is (OSC 7).
//!
//! The Git tool has to know which repository the terminal is in, and the only answer that follows a
//! `cd` — on every platform, without querying process internals per OS — is the shell saying so
//! itself. `OSC 7` is the sequence for that (`ESC ] 7 ; file://<host><path> ST`); iTerm2 and VS Code
//! use exactly this.
//!
//! Almost no shell emits it unprompted, so a hook has to be installed. **Never by editing the user's
//! files.** Instead a generated rc file is placed in this app's own data directory and the shell is
//! pointed at it for this session only; that file's first job is to source the user's real
//! configuration, so nothing they have set is lost.
//!
//! **It fails soft, always.** If the file cannot be written, or the shell is one this does not know,
//! the session starts exactly as it would have — without cwd reporting. A terminal that refuses to
//! open because an optional convenience could not be installed would be a far worse trade.

use std::path::{Path, PathBuf};
use std::sync::OnceLock;

/// Where the generated rc files live. Set once at startup from the resolved app-data directory.
static DIR: OnceLock<PathBuf> = OnceLock::new();

/// Point shell integration at `<app_data_dir>/shell/`. Called from `setup()`.
pub fn set_data_dir(dir: &Path) {
    let _ = DIR.set(dir.join("shell"));
}

/// What a shell needs to start with the hook installed: extra arguments and environment.
#[derive(Debug, Default, PartialEq, Eq)]
pub struct Integration {
    pub args: Vec<String>,
    pub env: Vec<(String, String)>,
}

/// Prepare integration for `program`, or `Integration::default()` when it cannot be provided.
///
/// Returning an empty integration is the "not available" answer, and it is deliberately
/// indistinguishable to the caller from "not needed": both mean *start the shell plainly*.
pub fn prepare(program: &str) -> Integration {
    let Some(dir) = DIR.get() else {
        return Integration::default();
    };
    match shell_kind(program) {
        Some(Kind::Zsh) => zsh(dir),
        Some(Kind::Bash) => bash(dir),
        // fish emits OSC 7 by itself, and an unknown shell is not one to experiment on.
        None => Integration::default(),
    }
}

enum Kind {
    Zsh,
    Bash,
}

/// Matched on the file name so `/opt/homebrew/bin/zsh` and `/bin/zsh` are the same shell.
fn shell_kind(program: &str) -> Option<Kind> {
    let name = Path::new(program)
        .file_stem()?
        .to_string_lossy()
        .to_string();
    match name.as_str() {
        "zsh" => Some(Kind::Zsh),
        "bash" => Some(Kind::Bash),
        _ => None,
    }
}

/// The hook itself, in POSIX-ish shell.
///
/// Plain OSC 7, with no tmux handling of any kind — **inside tmux this integration is not installed
/// at all**. tmux consumes OSC 7 for its own `pane_current_path` and does not forward it; wrapping it
/// in tmux's DCS passthrough was tried and measured, and nothing arrived at the outer terminal. What
/// does work there is asking tmux (`terminal::tmux::pane_cwd`), which has the further advantage of
/// answering for a session that already existed and could never have had a hook injected into it. So
/// the two cases are cleanly split, and a tmux user's shell starts completely untouched.
///
/// **Defined only — never called here.** It used to run once at the end of the rc file, on the theory
/// that the first reading should not wait for the user to press Enter. It does not have to: `precmd`
/// (zsh) and `PROMPT_COMMAND` (bash) both run before the *first* prompt as well, so the immediate call
/// bought nothing — and it wrote to the terminal at an unpredictable point in someone else's startup.
/// With powerlevel10k's instant prompt that point is mid-line, which leaves zsh convinced the previous
/// output had no trailing newline and makes it print its `%` end-of-line mark at the top of every
/// fresh terminal.
fn hook(host_var: &str) -> String {
    format!(
        r#"
_yggshell_report_cwd() {{
  printf '\033]7;file://%s%s\033\\' "${{{host_var}:-}}" "$PWD"
}}
"#
    )
}

fn zsh(dir: &Path) -> Integration {
    // zsh resolves `$ZDOTDIR/.zshenv`, then `$ZDOTDIR/.zshrc`, re-reading the variable each time.
    // That is the whole difficulty: our directory has to be in place long enough for our files to be
    // found, and OUT OF THE WAY while the user's own configuration runs.
    //
    // Getting this wrong is not cosmetic. A `~/.zshenv` — or oh-my-zsh — that computes
    // `HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history` will happily point the user's shell history at OUR
    // directory, and then every terminal opens with an empty history and writes to a file nobody will
    // ever look at again. `.zcompdump` goes the same way, which degrades completion.
    //
    // So ZDOTDIR is restored *around each hand-off* rather than once at the end.
    let zshenv =
        r#"# Generated by YggShell for this session only. Do not edit; it is rewritten on launch.
# The user's .zshenv must run with the ZDOTDIR IT expects: anything it derives from that variable —
# HISTFILE, .zcompdump — would otherwise be redirected into this app's data directory.
YGGSHELL_OURS="$ZDOTDIR"
export ZDOTDIR="${YGGSHELL_ZDOTDIR_ORIG:-$HOME}"
[ -f "$ZDOTDIR/.zshenv" ] && . "$ZDOTDIR/.zshenv"
# Put ours back, or zsh looks for .zshrc in the user's directory and this integration disappears.
export ZDOTDIR="$YGGSHELL_OURS"
"#
        .to_string();

    let zshrc = format!(
        r#"# Generated by YggShell for this session only. Do not edit; it is rewritten on launch.
# From here on the real ZDOTDIR stands, for the same reason as in .zshenv — and nothing of ours needs
# it any more, because this is the last file zsh reads from our directory.
export ZDOTDIR="${{YGGSHELL_ZDOTDIR_ORIG:-$HOME}}"
# Repair what the SYSTEM rc did. /etc/zshrc runs between our .zshenv and this file, and on macOS it
# contains `HISTFILE=${{ZDOTDIR:-$HOME}}/.zsh_history` — which at that moment is OUR directory. Left
# alone, every terminal opens with an empty history and writes to a file nobody will ever read.
# Only a value that points into our directory is touched; anything the user chose is left alone.
[ "${{HISTFILE:-}}" = "$YGGSHELL_OURS/.zsh_history" ] && HISTFILE="$ZDOTDIR/.zsh_history"
unset YGGSHELL_OURS
# The user's configuration runs FIRST, so the hook below cannot be undone by it — and so their own
# HISTFILE, set here, still wins over the repair above.
[ -f "$ZDOTDIR/.zshrc" ] && . "$ZDOTDIR/.zshrc"
{hook}
autoload -Uz add-zsh-hook 2>/dev/null && add-zsh-hook precmd _yggshell_report_cwd 2>/dev/null \
  || precmd_functions+=(_yggshell_report_cwd)
"#,
        hook = hook("HOST")
    );

    let Some(written) = write_rc(dir, &[(".zshenv", &zshenv), (".zshrc", &zshrc)]) else {
        return Integration::default();
    };

    let mut env = vec![(
        "ZDOTDIR".to_string(),
        written.to_string_lossy().into_owned(),
    )];
    // Remembered so the generated files can hand the real value back. Only meaningful when the user
    // had one; otherwise `$HOME` is the correct answer and the files default to it.
    if let Ok(original) = std::env::var("ZDOTDIR") {
        env.push(("YGGSHELL_ZDOTDIR_ORIG".to_string(), original));
    }
    Integration {
        args: Vec::new(),
        env,
    }
}

fn bash(dir: &Path) -> Integration {
    let rc = format!(
        r#"# Generated by YggShell for this session only. Do not edit; it is rewritten on launch.
# --rcfile REPLACES ~/.bashrc, so the user's own file is sourced here first.
[ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"
{hook}
PROMPT_COMMAND="_yggshell_report_cwd${{PROMPT_COMMAND:+;$PROMPT_COMMAND}}"
"#,
        hook = hook("HOSTNAME")
    );

    let Some(written) = write_rc(dir, &[("bashrc", &rc)]) else {
        return Integration::default();
    };
    Integration {
        // `-i` because --rcfile is only honoured by an interactive shell.
        args: vec![
            "--rcfile".to_string(),
            written.join("bashrc").to_string_lossy().into_owned(),
            "-i".to_string(),
        ],
        env: Vec::new(),
    }
}

/// Write the generated files, returning the directory they are in. `None` on any failure — the
/// caller then starts the shell without integration rather than not at all.
fn write_rc(dir: &Path, files: &[(&str, &String)]) -> Option<PathBuf> {
    if let Err(e) = std::fs::create_dir_all(dir) {
        tracing::warn!(path = %dir.display(), error = %e, "shell integration unavailable");
        return None;
    }
    for (name, contents) in files {
        if let Err(e) = std::fs::write(dir.join(name), contents.as_bytes()) {
            tracing::warn!(file = %name, error = %e, "shell integration unavailable");
            return None;
        }
    }
    Some(dir.to_path_buf())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_shell_is_recognised_by_its_name_not_its_path() {
        assert!(matches!(
            shell_kind("/opt/homebrew/bin/zsh"),
            Some(Kind::Zsh)
        ));
        assert!(matches!(shell_kind("/bin/bash"), Some(Kind::Bash)));
        assert!(matches!(shell_kind("bash"), Some(Kind::Bash)));
    }

    #[test]
    fn an_unknown_shell_gets_no_integration() {
        // fish reports its own cwd, and a shell nobody tested is not one to inject a hook into.
        assert!(shell_kind("/usr/bin/fish").is_none());
        assert!(shell_kind("/usr/bin/nu").is_none());
    }

    #[test]
    fn the_generated_zsh_config_sources_the_users_own_first() {
        let dir = tempfile::tempdir().expect("tempdir");
        let integration = zsh(dir.path());

        let zshrc = std::fs::read_to_string(dir.path().join(".zshrc")).expect("zshrc");
        // Order matters: the user's configuration must run before the hook is added, or their config
        // could undo it.
        // The system rc (/etc/zshrc on macOS) sets HISTFILE from ZDOTDIR *between* our two files.
        // Without this line the user's shell history is redirected into this app's data directory.
        assert!(zshrc.contains(r#"[ "${HISTFILE:-}" = "$YGGSHELL_OURS/.zsh_history" ]"#));
        let restores = zshrc.find("export ZDOTDIR=").expect("restores ZDOTDIR");
        let sources_user = zshrc
            .find(". \"$ZDOTDIR/.zshrc\"")
            .expect("sources the user's zshrc");
        let installs_hook = zshrc.find("add-zsh-hook").expect("installs the hook");
        assert!(
            restores < sources_user,
            "ZDOTDIR is real before their config reads it"
        );
        assert!(sources_user < installs_hook);
        // The hook is DEFINED here and left to precmd to call. Calling it inline wrote to the
        // terminal at an unpredictable point in the user's own startup — see `hook`.
        assert!(!zshrc.contains("\n_yggshell_report_cwd\n"));

        assert!(integration
            .env
            .iter()
            .any(|(k, v)| k == "ZDOTDIR" && v == &dir.path().to_string_lossy()));
    }

    #[test]
    fn the_users_zshenv_runs_with_their_own_zdotdir() {
        // The defect this pins: a ~/.zshenv (or oh-my-zsh) that derives HISTFILE or .zcompdump from
        // ${ZDOTDIR:-$HOME} would otherwise redirect the user's shell history into this app's data
        // directory — so every terminal opened with an empty history and wrote to a file nobody would
        // ever read again.
        let dir = tempfile::tempdir().expect("tempdir");
        zsh(dir.path());
        let zshenv = std::fs::read_to_string(dir.path().join(".zshenv")).expect("zshenv");

        let restores = zshenv
            .find(r#"export ZDOTDIR="${YGGSHELL_ZDOTDIR_ORIG:-$HOME}""#)
            .expect("restores the real ZDOTDIR");
        let sources_user = zshenv
            .find(r#". "$ZDOTDIR/.zshenv""#)
            .expect("sources the user's zshenv");
        let puts_ours_back = zshenv
            .rfind(r#"export ZDOTDIR="$YGGSHELL_OURS""#)
            .expect("puts our directory back");

        assert!(
            restores < sources_user,
            "their zshenv must see their ZDOTDIR"
        );
        // And ours has to be back afterwards, or zsh looks for .zshrc in their directory and the
        // whole integration silently disappears.
        assert!(sources_user < puts_ours_back);
    }

    #[test]
    fn the_generated_bash_config_replaces_nothing() {
        let dir = tempfile::tempdir().expect("tempdir");
        let integration = bash(dir.path());

        let rc = std::fs::read_to_string(dir.path().join("bashrc")).expect("bashrc");
        // --rcfile REPLACES ~/.bashrc; without this line the user's whole shell config would vanish
        // the moment they opened a terminal here.
        assert!(rc.contains(r#". "$HOME/.bashrc""#));
        // Prepended, not overwritten: a PROMPT_COMMAND the user already had must keep running.
        assert!(rc.contains(r#"${PROMPT_COMMAND:+;$PROMPT_COMMAND}"#));
        // Defined, never called here: writing to the terminal mid-startup is what made zsh print its
        // end-of-line mark at the top of every fresh terminal.
        assert!(!rc.contains("\n_yggshell_report_cwd\n"));
        assert!(integration.args.contains(&"--rcfile".to_string()));
        assert!(integration.args.contains(&"-i".to_string()));
    }

    #[test]
    fn an_unwritable_directory_costs_the_hook_not_the_terminal() {
        let file = tempfile::NamedTempFile::new().expect("tempfile");
        // A path that is a file, not a directory: create_dir_all fails.
        let integration = zsh(&file.path().join("nope"));
        assert_eq!(integration, Integration::default());
    }
}
