//! Teaching the user's shell to report where it is (OSC 7).
//!
//! The Git tool has to know which repository the terminal is in, and the only answer that follows a
//! `cd` — on every platform, without querying process internals per OS — is the shell saying so
//! itself. `OSC 7` is the sequence for that (`ESC ] 7 ; file://<host><path> ST`); iTerm2 and VS Code
//! use exactly this.
//!
//! Almost no shell emits it unprompted, so a hook has to be installed. **Never by editing the user's
//! files.** Instead a generated rc file is placed in this app's own data directory and the shell is
//! pointed at it for this session only; that file's first job is to source the user's real
//! configuration, so nothing they have set is lost.
//!
//! **It fails soft, always.** If the file cannot be written, or the shell is one this does not know,
//! the session starts exactly as it would have — without cwd reporting. A terminal that refuses to
//! open because an optional convenience could not be installed would be a far worse trade.

use std::path::{Path, PathBuf};
use std::sync::OnceLock;

/// Where the generated rc files live. Set once at startup from the resolved app-data directory.
static DIR: OnceLock<PathBuf> = OnceLock::new();

/// Point shell integration at `<app_data_dir>/shell/`. Called from `setup()`.
pub fn set_data_dir(dir: &Path) {
    let _ = DIR.set(dir.join("shell"));
}

/// What a shell needs to start with the hook installed: extra arguments and environment.
#[derive(Debug, Default, PartialEq, Eq)]
pub struct Integration {
    pub args: Vec<String>,
    pub env: Vec<(String, String)>,
}

/// Prepare integration for `program`, or `Integration::default()` when it cannot be provided.
///
/// Returning an empty integration is the "not available" answer, and it is deliberately
/// indistinguishable to the caller from "not needed": both mean *start the shell plainly*.
pub fn prepare(program: &str) -> Integration {
    let Some(dir) = DIR.get() else {
        return Integration::default();
    };
    match shell_kind(program) {
        Some(Kind::Zsh) => zsh(dir),
        Some(Kind::Bash) => bash(dir),
        // fish emits OSC 7 by itself, and an unknown shell is not one to experiment on.
        None => Integration::default(),
    }
}

enum Kind {
    Zsh,
    Bash,
}

/// Matched on the file name so `/opt/homebrew/bin/zsh` and `/bin/zsh` are the same shell.
fn shell_kind(program: &str) -> Option<Kind> {
    let name = Path::new(program)
        .file_stem()?
        .to_string_lossy()
        .to_string();
    match name.as_str() {
        "zsh" => Some(Kind::Zsh),
        "bash" => Some(Kind::Bash),
        _ => None,
    }
}

/// The hook itself, in POSIX-ish shell. Emitted after every prompt, and once at start so the first
/// reading does not wait for the user to press Enter.
fn hook(host_var: &str) -> String {
    format!(
        r#"
_yggshell_report_cwd() {{
  printf '\033]7;file://%s%s\033\\' "${{{host_var}:-}}" "$PWD"
}}
_yggshell_report_cwd
"#
    )
}

fn zsh(dir: &Path) -> Integration {
    // zsh looks for .zshenv and .zshrc in $ZDOTDIR. Both are generated, and both chain to the user's
    // real ones — with ZDOTDIR restored first, so their own config sees the value it expects rather
    // than ours.
    let zshenv =
        r#"# Generated by YggShell for this session only. Do not edit; it is rewritten on launch.
YGGSHELL_ZDOTDIR_ORIG="${YGGSHELL_ZDOTDIR_ORIG:-$HOME}"
[ -f "$YGGSHELL_ZDOTDIR_ORIG/.zshenv" ] && . "$YGGSHELL_ZDOTDIR_ORIG/.zshenv"
"#
        .to_string();

    let zshrc = format!(
        r#"# Generated by YggShell for this session only. Do not edit; it is rewritten on launch.
YGGSHELL_ZDOTDIR_ORIG="${{YGGSHELL_ZDOTDIR_ORIG:-$HOME}}"
# The user's configuration runs FIRST and with the real ZDOTDIR, so nothing it sets is lost and
# nothing it reads is a lie.
export ZDOTDIR="$YGGSHELL_ZDOTDIR_ORIG"
[ -f "$YGGSHELL_ZDOTDIR_ORIG/.zshrc" ] && . "$YGGSHELL_ZDOTDIR_ORIG/.zshrc"
{hook}
autoload -Uz add-zsh-hook 2>/dev/null && add-zsh-hook precmd _yggshell_report_cwd 2>/dev/null \
  || precmd_functions+=(_yggshell_report_cwd)
"#,
        hook = hook("HOST")
    );

    let Some(written) = write_rc(dir, &[(".zshenv", &zshenv), (".zshrc", &zshrc)]) else {
        return Integration::default();
    };

    let mut env = vec![(
        "ZDOTDIR".to_string(),
        written.to_string_lossy().into_owned(),
    )];
    // Remembered so the generated files can hand the real value back.
    if let Ok(original) = std::env::var("ZDOTDIR") {
        env.push(("YGGSHELL_ZDOTDIR_ORIG".to_string(), original));
    }
    Integration {
        args: Vec::new(),
        env,
    }
}

fn bash(dir: &Path) -> Integration {
    let rc = format!(
        r#"# Generated by YggShell for this session only. Do not edit; it is rewritten on launch.
# --rcfile REPLACES ~/.bashrc, so the user's own file is sourced here first.
[ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"
{hook}
PROMPT_COMMAND="_yggshell_report_cwd${{PROMPT_COMMAND:+;$PROMPT_COMMAND}}"
"#,
        hook = hook("HOSTNAME")
    );

    let Some(written) = write_rc(dir, &[("bashrc", &rc)]) else {
        return Integration::default();
    };
    Integration {
        // `-i` because --rcfile is only honoured by an interactive shell.
        args: vec![
            "--rcfile".to_string(),
            written.join("bashrc").to_string_lossy().into_owned(),
            "-i".to_string(),
        ],
        env: Vec::new(),
    }
}

/// Write the generated files, returning the directory they are in. `None` on any failure — the
/// caller then starts the shell without integration rather than not at all.
fn write_rc(dir: &Path, files: &[(&str, &String)]) -> Option<PathBuf> {
    if let Err(e) = std::fs::create_dir_all(dir) {
        tracing::warn!(path = %dir.display(), error = %e, "shell integration unavailable");
        return None;
    }
    for (name, contents) in files {
        if let Err(e) = std::fs::write(dir.join(name), contents.as_bytes()) {
            tracing::warn!(file = %name, error = %e, "shell integration unavailable");
            return None;
        }
    }
    Some(dir.to_path_buf())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_shell_is_recognised_by_its_name_not_its_path() {
        assert!(matches!(
            shell_kind("/opt/homebrew/bin/zsh"),
            Some(Kind::Zsh)
        ));
        assert!(matches!(shell_kind("/bin/bash"), Some(Kind::Bash)));
        assert!(matches!(shell_kind("bash"), Some(Kind::Bash)));
    }

    #[test]
    fn an_unknown_shell_gets_no_integration() {
        // fish reports its own cwd, and a shell nobody tested is not one to inject a hook into.
        assert!(shell_kind("/usr/bin/fish").is_none());
        assert!(shell_kind("/usr/bin/nu").is_none());
    }

    #[test]
    fn the_generated_zsh_config_sources_the_users_own_first() {
        let dir = tempfile::tempdir().expect("tempdir");
        let integration = zsh(dir.path());

        let zshrc = std::fs::read_to_string(dir.path().join(".zshrc")).expect("zshrc");
        // Order matters: the user's configuration must run before the hook is added, and it must see
        // the real ZDOTDIR — otherwise a config that reads it would be handed our directory.
        let sources_user = zshrc.find(".zshrc\"").expect("sources the user's zshrc");
        let installs_hook = zshrc.find("add-zsh-hook").expect("installs the hook");
        assert!(sources_user < installs_hook);
        assert!(zshrc.contains(r#"export ZDOTDIR="$YGGSHELL_ZDOTDIR_ORIG""#));

        assert!(integration
            .env
            .iter()
            .any(|(k, v)| k == "ZDOTDIR" && v == &dir.path().to_string_lossy()));
    }

    #[test]
    fn the_generated_bash_config_replaces_nothing() {
        let dir = tempfile::tempdir().expect("tempdir");
        let integration = bash(dir.path());

        let rc = std::fs::read_to_string(dir.path().join("bashrc")).expect("bashrc");
        // --rcfile REPLACES ~/.bashrc; without this line the user's whole shell config would vanish
        // the moment they opened a terminal here.
        assert!(rc.contains(r#". "$HOME/.bashrc""#));
        // Prepended, not overwritten: a PROMPT_COMMAND the user already had must keep running.
        assert!(rc.contains(r#"${PROMPT_COMMAND:+;$PROMPT_COMMAND}"#));
        assert!(integration.args.contains(&"--rcfile".to_string()));
        assert!(integration.args.contains(&"-i".to_string()));
    }

    #[test]
    fn an_unwritable_directory_costs_the_hook_not_the_terminal() {
        let file = tempfile::NamedTempFile::new().expect("tempfile");
        // A path that is a file, not a directory: create_dir_all fails.
        let integration = zsh(&file.path().join("nope"));
        assert_eq!(integration, Integration::default());
    }
}
